// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: app.proto

package org.envirocar.server.rest;

public final class StatisticProto {
  private StatisticProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface StatisticOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Statistic)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required double max = 1;</code>
     * @return Whether the max field is set.
     */
    boolean hasMax();
    /**
     * <code>required double max = 1;</code>
     * @return The max.
     */
    double getMax();

    /**
     * <code>required double avg = 2;</code>
     * @return Whether the avg field is set.
     */
    boolean hasAvg();
    /**
     * <code>required double avg = 2;</code>
     * @return The avg.
     */
    double getAvg();

    /**
     * <code>required double min = 3;</code>
     * @return Whether the min field is set.
     */
    boolean hasMin();
    /**
     * <code>required double min = 3;</code>
     * @return The min.
     */
    double getMin();

    /**
     * <code>required int64 measurement = 4;</code>
     * @return Whether the measurement field is set.
     */
    boolean hasMeasurement();
    /**
     * <code>required int64 measurement = 4;</code>
     * @return The measurement.
     */
    long getMeasurement();

    /**
     * <code>required int64 tracks = 5;</code>
     * @return Whether the tracks field is set.
     */
    boolean hasTracks();
    /**
     * <code>required int64 tracks = 5;</code>
     * @return The tracks.
     */
    long getTracks();

    /**
     * <code>required int64 sensors = 6;</code>
     * @return Whether the sensors field is set.
     */
    boolean hasSensors();
    /**
     * <code>required int64 sensors = 6;</code>
     * @return The sensors.
     */
    long getSensors();
  }
  /**
   * Protobuf type {@code Statistic}
   */
  public  static final class Statistic extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Statistic)
      StatisticOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Statistic.newBuilder() to construct.
    private Statistic(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Statistic() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Statistic();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Statistic(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {
              bitField0_ |= 0x00000001;
              max_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              avg_ = input.readDouble();
              break;
            }
            case 25: {
              bitField0_ |= 0x00000004;
              min_ = input.readDouble();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              measurement_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              tracks_ = input.readInt64();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              sensors_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.envirocar.server.rest.StatisticProto.internal_static_Statistic_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.envirocar.server.rest.StatisticProto.internal_static_Statistic_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.envirocar.server.rest.StatisticProto.Statistic.class, org.envirocar.server.rest.StatisticProto.Statistic.Builder.class);
    }

    private int bitField0_;
    public static final int MAX_FIELD_NUMBER = 1;
    private double max_;
    /**
     * <code>required double max = 1;</code>
     * @return Whether the max field is set.
     */
    public boolean hasMax() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required double max = 1;</code>
     * @return The max.
     */
    public double getMax() {
      return max_;
    }

    public static final int AVG_FIELD_NUMBER = 2;
    private double avg_;
    /**
     * <code>required double avg = 2;</code>
     * @return Whether the avg field is set.
     */
    public boolean hasAvg() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required double avg = 2;</code>
     * @return The avg.
     */
    public double getAvg() {
      return avg_;
    }

    public static final int MIN_FIELD_NUMBER = 3;
    private double min_;
    /**
     * <code>required double min = 3;</code>
     * @return Whether the min field is set.
     */
    public boolean hasMin() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required double min = 3;</code>
     * @return The min.
     */
    public double getMin() {
      return min_;
    }

    public static final int MEASUREMENT_FIELD_NUMBER = 4;
    private long measurement_;
    /**
     * <code>required int64 measurement = 4;</code>
     * @return Whether the measurement field is set.
     */
    public boolean hasMeasurement() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required int64 measurement = 4;</code>
     * @return The measurement.
     */
    public long getMeasurement() {
      return measurement_;
    }

    public static final int TRACKS_FIELD_NUMBER = 5;
    private long tracks_;
    /**
     * <code>required int64 tracks = 5;</code>
     * @return Whether the tracks field is set.
     */
    public boolean hasTracks() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required int64 tracks = 5;</code>
     * @return The tracks.
     */
    public long getTracks() {
      return tracks_;
    }

    public static final int SENSORS_FIELD_NUMBER = 6;
    private long sensors_;
    /**
     * <code>required int64 sensors = 6;</code>
     * @return Whether the sensors field is set.
     */
    public boolean hasSensors() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required int64 sensors = 6;</code>
     * @return The sensors.
     */
    public long getSensors() {
      return sensors_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasMax()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAvg()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMin()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMeasurement()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTracks()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSensors()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeDouble(1, max_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeDouble(2, avg_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeDouble(3, min_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeInt64(4, measurement_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeInt64(5, tracks_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeInt64(6, sensors_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, max_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, avg_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, min_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, measurement_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, tracks_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, sensors_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.envirocar.server.rest.StatisticProto.Statistic)) {
        return super.equals(obj);
      }
      org.envirocar.server.rest.StatisticProto.Statistic other = (org.envirocar.server.rest.StatisticProto.Statistic) obj;

      if (hasMax() != other.hasMax()) return false;
      if (hasMax()) {
        if (java.lang.Double.doubleToLongBits(getMax())
            != java.lang.Double.doubleToLongBits(
                other.getMax())) return false;
      }
      if (hasAvg() != other.hasAvg()) return false;
      if (hasAvg()) {
        if (java.lang.Double.doubleToLongBits(getAvg())
            != java.lang.Double.doubleToLongBits(
                other.getAvg())) return false;
      }
      if (hasMin() != other.hasMin()) return false;
      if (hasMin()) {
        if (java.lang.Double.doubleToLongBits(getMin())
            != java.lang.Double.doubleToLongBits(
                other.getMin())) return false;
      }
      if (hasMeasurement() != other.hasMeasurement()) return false;
      if (hasMeasurement()) {
        if (getMeasurement()
            != other.getMeasurement()) return false;
      }
      if (hasTracks() != other.hasTracks()) return false;
      if (hasTracks()) {
        if (getTracks()
            != other.getTracks()) return false;
      }
      if (hasSensors() != other.hasSensors()) return false;
      if (hasSensors()) {
        if (getSensors()
            != other.getSensors()) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMax()) {
        hash = (37 * hash) + MAX_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getMax()));
      }
      if (hasAvg()) {
        hash = (37 * hash) + AVG_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getAvg()));
      }
      if (hasMin()) {
        hash = (37 * hash) + MIN_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            java.lang.Double.doubleToLongBits(getMin()));
      }
      if (hasMeasurement()) {
        hash = (37 * hash) + MEASUREMENT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getMeasurement());
      }
      if (hasTracks()) {
        hash = (37 * hash) + TRACKS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getTracks());
      }
      if (hasSensors()) {
        hash = (37 * hash) + SENSORS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getSensors());
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.envirocar.server.rest.StatisticProto.Statistic parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.envirocar.server.rest.StatisticProto.Statistic parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.envirocar.server.rest.StatisticProto.Statistic parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.envirocar.server.rest.StatisticProto.Statistic parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.envirocar.server.rest.StatisticProto.Statistic parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.envirocar.server.rest.StatisticProto.Statistic parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.envirocar.server.rest.StatisticProto.Statistic parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.envirocar.server.rest.StatisticProto.Statistic parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.envirocar.server.rest.StatisticProto.Statistic parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.envirocar.server.rest.StatisticProto.Statistic parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.envirocar.server.rest.StatisticProto.Statistic parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.envirocar.server.rest.StatisticProto.Statistic parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.envirocar.server.rest.StatisticProto.Statistic prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Statistic}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Statistic)
        org.envirocar.server.rest.StatisticProto.StatisticOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.envirocar.server.rest.StatisticProto.internal_static_Statistic_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.envirocar.server.rest.StatisticProto.internal_static_Statistic_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.envirocar.server.rest.StatisticProto.Statistic.class, org.envirocar.server.rest.StatisticProto.Statistic.Builder.class);
      }

      // Construct using org.envirocar.server.rest.StatisticProto.Statistic.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        max_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        avg_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        min_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000004);
        measurement_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        tracks_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        sensors_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.envirocar.server.rest.StatisticProto.internal_static_Statistic_descriptor;
      }

      @java.lang.Override
      public org.envirocar.server.rest.StatisticProto.Statistic getDefaultInstanceForType() {
        return org.envirocar.server.rest.StatisticProto.Statistic.getDefaultInstance();
      }

      @java.lang.Override
      public org.envirocar.server.rest.StatisticProto.Statistic build() {
        org.envirocar.server.rest.StatisticProto.Statistic result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.envirocar.server.rest.StatisticProto.Statistic buildPartial() {
        org.envirocar.server.rest.StatisticProto.Statistic result = new org.envirocar.server.rest.StatisticProto.Statistic(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.max_ = max_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.avg_ = avg_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.min_ = min_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.measurement_ = measurement_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.tracks_ = tracks_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.sensors_ = sensors_;
          to_bitField0_ |= 0x00000020;
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.envirocar.server.rest.StatisticProto.Statistic) {
          return mergeFrom((org.envirocar.server.rest.StatisticProto.Statistic)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.envirocar.server.rest.StatisticProto.Statistic other) {
        if (other == org.envirocar.server.rest.StatisticProto.Statistic.getDefaultInstance()) return this;
        if (other.hasMax()) {
          setMax(other.getMax());
        }
        if (other.hasAvg()) {
          setAvg(other.getAvg());
        }
        if (other.hasMin()) {
          setMin(other.getMin());
        }
        if (other.hasMeasurement()) {
          setMeasurement(other.getMeasurement());
        }
        if (other.hasTracks()) {
          setTracks(other.getTracks());
        }
        if (other.hasSensors()) {
          setSensors(other.getSensors());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasMax()) {
          return false;
        }
        if (!hasAvg()) {
          return false;
        }
        if (!hasMin()) {
          return false;
        }
        if (!hasMeasurement()) {
          return false;
        }
        if (!hasTracks()) {
          return false;
        }
        if (!hasSensors()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.envirocar.server.rest.StatisticProto.Statistic parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.envirocar.server.rest.StatisticProto.Statistic) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double max_ ;
      /**
       * <code>required double max = 1;</code>
       * @return Whether the max field is set.
       */
      public boolean hasMax() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required double max = 1;</code>
       * @return The max.
       */
      public double getMax() {
        return max_;
      }
      /**
       * <code>required double max = 1;</code>
       * @param value The max to set.
       * @return This builder for chaining.
       */
      public Builder setMax(double value) {
        bitField0_ |= 0x00000001;
        max_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double max = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearMax() {
        bitField0_ = (bitField0_ & ~0x00000001);
        max_ = 0D;
        onChanged();
        return this;
      }

      private double avg_ ;
      /**
       * <code>required double avg = 2;</code>
       * @return Whether the avg field is set.
       */
      public boolean hasAvg() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required double avg = 2;</code>
       * @return The avg.
       */
      public double getAvg() {
        return avg_;
      }
      /**
       * <code>required double avg = 2;</code>
       * @param value The avg to set.
       * @return This builder for chaining.
       */
      public Builder setAvg(double value) {
        bitField0_ |= 0x00000002;
        avg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double avg = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearAvg() {
        bitField0_ = (bitField0_ & ~0x00000002);
        avg_ = 0D;
        onChanged();
        return this;
      }

      private double min_ ;
      /**
       * <code>required double min = 3;</code>
       * @return Whether the min field is set.
       */
      public boolean hasMin() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required double min = 3;</code>
       * @return The min.
       */
      public double getMin() {
        return min_;
      }
      /**
       * <code>required double min = 3;</code>
       * @param value The min to set.
       * @return This builder for chaining.
       */
      public Builder setMin(double value) {
        bitField0_ |= 0x00000004;
        min_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double min = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMin() {
        bitField0_ = (bitField0_ & ~0x00000004);
        min_ = 0D;
        onChanged();
        return this;
      }

      private long measurement_ ;
      /**
       * <code>required int64 measurement = 4;</code>
       * @return Whether the measurement field is set.
       */
      public boolean hasMeasurement() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required int64 measurement = 4;</code>
       * @return The measurement.
       */
      public long getMeasurement() {
        return measurement_;
      }
      /**
       * <code>required int64 measurement = 4;</code>
       * @param value The measurement to set.
       * @return This builder for chaining.
       */
      public Builder setMeasurement(long value) {
        bitField0_ |= 0x00000008;
        measurement_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 measurement = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMeasurement() {
        bitField0_ = (bitField0_ & ~0x00000008);
        measurement_ = 0L;
        onChanged();
        return this;
      }

      private long tracks_ ;
      /**
       * <code>required int64 tracks = 5;</code>
       * @return Whether the tracks field is set.
       */
      public boolean hasTracks() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required int64 tracks = 5;</code>
       * @return The tracks.
       */
      public long getTracks() {
        return tracks_;
      }
      /**
       * <code>required int64 tracks = 5;</code>
       * @param value The tracks to set.
       * @return This builder for chaining.
       */
      public Builder setTracks(long value) {
        bitField0_ |= 0x00000010;
        tracks_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 tracks = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTracks() {
        bitField0_ = (bitField0_ & ~0x00000010);
        tracks_ = 0L;
        onChanged();
        return this;
      }

      private long sensors_ ;
      /**
       * <code>required int64 sensors = 6;</code>
       * @return Whether the sensors field is set.
       */
      public boolean hasSensors() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required int64 sensors = 6;</code>
       * @return The sensors.
       */
      public long getSensors() {
        return sensors_;
      }
      /**
       * <code>required int64 sensors = 6;</code>
       * @param value The sensors to set.
       * @return This builder for chaining.
       */
      public Builder setSensors(long value) {
        bitField0_ |= 0x00000020;
        sensors_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 sensors = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearSensors() {
        bitField0_ = (bitField0_ & ~0x00000020);
        sensors_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Statistic)
    }

    // @@protoc_insertion_point(class_scope:Statistic)
    private static final org.envirocar.server.rest.StatisticProto.Statistic DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.envirocar.server.rest.StatisticProto.Statistic();
    }

    public static org.envirocar.server.rest.StatisticProto.Statistic getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Statistic>
        PARSER = new com.google.protobuf.AbstractParser<Statistic>() {
      @java.lang.Override
      public Statistic parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Statistic(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Statistic> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Statistic> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.envirocar.server.rest.StatisticProto.Statistic getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StatisticsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Statistics)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .Statistic stats = 1;</code>
     */
    java.util.List<org.envirocar.server.rest.StatisticProto.Statistic> 
        getStatsList();
    /**
     * <code>repeated .Statistic stats = 1;</code>
     */
    org.envirocar.server.rest.StatisticProto.Statistic getStats(int index);
    /**
     * <code>repeated .Statistic stats = 1;</code>
     */
    int getStatsCount();
    /**
     * <code>repeated .Statistic stats = 1;</code>
     */
    java.util.List<? extends org.envirocar.server.rest.StatisticProto.StatisticOrBuilder> 
        getStatsOrBuilderList();
    /**
     * <code>repeated .Statistic stats = 1;</code>
     */
    org.envirocar.server.rest.StatisticProto.StatisticOrBuilder getStatsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code Statistics}
   */
  public  static final class Statistics extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Statistics)
      StatisticsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Statistics.newBuilder() to construct.
    private Statistics(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Statistics() {
      stats_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Statistics();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Statistics(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                stats_ = new java.util.ArrayList<org.envirocar.server.rest.StatisticProto.Statistic>();
                mutable_bitField0_ |= 0x00000001;
              }
              stats_.add(
                  input.readMessage(org.envirocar.server.rest.StatisticProto.Statistic.PARSER, extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          stats_ = java.util.Collections.unmodifiableList(stats_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.envirocar.server.rest.StatisticProto.internal_static_Statistics_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.envirocar.server.rest.StatisticProto.internal_static_Statistics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.envirocar.server.rest.StatisticProto.Statistics.class, org.envirocar.server.rest.StatisticProto.Statistics.Builder.class);
    }

    public static final int STATS_FIELD_NUMBER = 1;
    private java.util.List<org.envirocar.server.rest.StatisticProto.Statistic> stats_;
    /**
     * <code>repeated .Statistic stats = 1;</code>
     */
    public java.util.List<org.envirocar.server.rest.StatisticProto.Statistic> getStatsList() {
      return stats_;
    }
    /**
     * <code>repeated .Statistic stats = 1;</code>
     */
    public java.util.List<? extends org.envirocar.server.rest.StatisticProto.StatisticOrBuilder> 
        getStatsOrBuilderList() {
      return stats_;
    }
    /**
     * <code>repeated .Statistic stats = 1;</code>
     */
    public int getStatsCount() {
      return stats_.size();
    }
    /**
     * <code>repeated .Statistic stats = 1;</code>
     */
    public org.envirocar.server.rest.StatisticProto.Statistic getStats(int index) {
      return stats_.get(index);
    }
    /**
     * <code>repeated .Statistic stats = 1;</code>
     */
    public org.envirocar.server.rest.StatisticProto.StatisticOrBuilder getStatsOrBuilder(
        int index) {
      return stats_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getStatsCount(); i++) {
        if (!getStats(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < stats_.size(); i++) {
        output.writeMessage(1, stats_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < stats_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, stats_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.envirocar.server.rest.StatisticProto.Statistics)) {
        return super.equals(obj);
      }
      org.envirocar.server.rest.StatisticProto.Statistics other = (org.envirocar.server.rest.StatisticProto.Statistics) obj;

      if (!getStatsList()
          .equals(other.getStatsList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getStatsCount() > 0) {
        hash = (37 * hash) + STATS_FIELD_NUMBER;
        hash = (53 * hash) + getStatsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.envirocar.server.rest.StatisticProto.Statistics parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.envirocar.server.rest.StatisticProto.Statistics parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.envirocar.server.rest.StatisticProto.Statistics parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.envirocar.server.rest.StatisticProto.Statistics parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.envirocar.server.rest.StatisticProto.Statistics parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.envirocar.server.rest.StatisticProto.Statistics parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.envirocar.server.rest.StatisticProto.Statistics parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.envirocar.server.rest.StatisticProto.Statistics parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.envirocar.server.rest.StatisticProto.Statistics parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.envirocar.server.rest.StatisticProto.Statistics parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.envirocar.server.rest.StatisticProto.Statistics parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.envirocar.server.rest.StatisticProto.Statistics parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.envirocar.server.rest.StatisticProto.Statistics prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Statistics}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Statistics)
        org.envirocar.server.rest.StatisticProto.StatisticsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.envirocar.server.rest.StatisticProto.internal_static_Statistics_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.envirocar.server.rest.StatisticProto.internal_static_Statistics_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.envirocar.server.rest.StatisticProto.Statistics.class, org.envirocar.server.rest.StatisticProto.Statistics.Builder.class);
      }

      // Construct using org.envirocar.server.rest.StatisticProto.Statistics.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getStatsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (statsBuilder_ == null) {
          stats_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          statsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.envirocar.server.rest.StatisticProto.internal_static_Statistics_descriptor;
      }

      @java.lang.Override
      public org.envirocar.server.rest.StatisticProto.Statistics getDefaultInstanceForType() {
        return org.envirocar.server.rest.StatisticProto.Statistics.getDefaultInstance();
      }

      @java.lang.Override
      public org.envirocar.server.rest.StatisticProto.Statistics build() {
        org.envirocar.server.rest.StatisticProto.Statistics result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.envirocar.server.rest.StatisticProto.Statistics buildPartial() {
        org.envirocar.server.rest.StatisticProto.Statistics result = new org.envirocar.server.rest.StatisticProto.Statistics(this);
        int from_bitField0_ = bitField0_;
        if (statsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            stats_ = java.util.Collections.unmodifiableList(stats_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.stats_ = stats_;
        } else {
          result.stats_ = statsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.envirocar.server.rest.StatisticProto.Statistics) {
          return mergeFrom((org.envirocar.server.rest.StatisticProto.Statistics)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.envirocar.server.rest.StatisticProto.Statistics other) {
        if (other == org.envirocar.server.rest.StatisticProto.Statistics.getDefaultInstance()) return this;
        if (statsBuilder_ == null) {
          if (!other.stats_.isEmpty()) {
            if (stats_.isEmpty()) {
              stats_ = other.stats_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureStatsIsMutable();
              stats_.addAll(other.stats_);
            }
            onChanged();
          }
        } else {
          if (!other.stats_.isEmpty()) {
            if (statsBuilder_.isEmpty()) {
              statsBuilder_.dispose();
              statsBuilder_ = null;
              stats_ = other.stats_;
              bitField0_ = (bitField0_ & ~0x00000001);
              statsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getStatsFieldBuilder() : null;
            } else {
              statsBuilder_.addAllMessages(other.stats_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getStatsCount(); i++) {
          if (!getStats(i).isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.envirocar.server.rest.StatisticProto.Statistics parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.envirocar.server.rest.StatisticProto.Statistics) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.envirocar.server.rest.StatisticProto.Statistic> stats_ =
        java.util.Collections.emptyList();
      private void ensureStatsIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          stats_ = new java.util.ArrayList<org.envirocar.server.rest.StatisticProto.Statistic>(stats_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.envirocar.server.rest.StatisticProto.Statistic, org.envirocar.server.rest.StatisticProto.Statistic.Builder, org.envirocar.server.rest.StatisticProto.StatisticOrBuilder> statsBuilder_;

      /**
       * <code>repeated .Statistic stats = 1;</code>
       */
      public java.util.List<org.envirocar.server.rest.StatisticProto.Statistic> getStatsList() {
        if (statsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(stats_);
        } else {
          return statsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Statistic stats = 1;</code>
       */
      public int getStatsCount() {
        if (statsBuilder_ == null) {
          return stats_.size();
        } else {
          return statsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Statistic stats = 1;</code>
       */
      public org.envirocar.server.rest.StatisticProto.Statistic getStats(int index) {
        if (statsBuilder_ == null) {
          return stats_.get(index);
        } else {
          return statsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Statistic stats = 1;</code>
       */
      public Builder setStats(
          int index, org.envirocar.server.rest.StatisticProto.Statistic value) {
        if (statsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStatsIsMutable();
          stats_.set(index, value);
          onChanged();
        } else {
          statsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Statistic stats = 1;</code>
       */
      public Builder setStats(
          int index, org.envirocar.server.rest.StatisticProto.Statistic.Builder builderForValue) {
        if (statsBuilder_ == null) {
          ensureStatsIsMutable();
          stats_.set(index, builderForValue.build());
          onChanged();
        } else {
          statsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Statistic stats = 1;</code>
       */
      public Builder addStats(org.envirocar.server.rest.StatisticProto.Statistic value) {
        if (statsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStatsIsMutable();
          stats_.add(value);
          onChanged();
        } else {
          statsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Statistic stats = 1;</code>
       */
      public Builder addStats(
          int index, org.envirocar.server.rest.StatisticProto.Statistic value) {
        if (statsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureStatsIsMutable();
          stats_.add(index, value);
          onChanged();
        } else {
          statsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Statistic stats = 1;</code>
       */
      public Builder addStats(
          org.envirocar.server.rest.StatisticProto.Statistic.Builder builderForValue) {
        if (statsBuilder_ == null) {
          ensureStatsIsMutable();
          stats_.add(builderForValue.build());
          onChanged();
        } else {
          statsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Statistic stats = 1;</code>
       */
      public Builder addStats(
          int index, org.envirocar.server.rest.StatisticProto.Statistic.Builder builderForValue) {
        if (statsBuilder_ == null) {
          ensureStatsIsMutable();
          stats_.add(index, builderForValue.build());
          onChanged();
        } else {
          statsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Statistic stats = 1;</code>
       */
      public Builder addAllStats(
          java.lang.Iterable<? extends org.envirocar.server.rest.StatisticProto.Statistic> values) {
        if (statsBuilder_ == null) {
          ensureStatsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, stats_);
          onChanged();
        } else {
          statsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Statistic stats = 1;</code>
       */
      public Builder clearStats() {
        if (statsBuilder_ == null) {
          stats_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          statsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Statistic stats = 1;</code>
       */
      public Builder removeStats(int index) {
        if (statsBuilder_ == null) {
          ensureStatsIsMutable();
          stats_.remove(index);
          onChanged();
        } else {
          statsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Statistic stats = 1;</code>
       */
      public org.envirocar.server.rest.StatisticProto.Statistic.Builder getStatsBuilder(
          int index) {
        return getStatsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Statistic stats = 1;</code>
       */
      public org.envirocar.server.rest.StatisticProto.StatisticOrBuilder getStatsOrBuilder(
          int index) {
        if (statsBuilder_ == null) {
          return stats_.get(index);  } else {
          return statsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Statistic stats = 1;</code>
       */
      public java.util.List<? extends org.envirocar.server.rest.StatisticProto.StatisticOrBuilder> 
           getStatsOrBuilderList() {
        if (statsBuilder_ != null) {
          return statsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(stats_);
        }
      }
      /**
       * <code>repeated .Statistic stats = 1;</code>
       */
      public org.envirocar.server.rest.StatisticProto.Statistic.Builder addStatsBuilder() {
        return getStatsFieldBuilder().addBuilder(
            org.envirocar.server.rest.StatisticProto.Statistic.getDefaultInstance());
      }
      /**
       * <code>repeated .Statistic stats = 1;</code>
       */
      public org.envirocar.server.rest.StatisticProto.Statistic.Builder addStatsBuilder(
          int index) {
        return getStatsFieldBuilder().addBuilder(
            index, org.envirocar.server.rest.StatisticProto.Statistic.getDefaultInstance());
      }
      /**
       * <code>repeated .Statistic stats = 1;</code>
       */
      public java.util.List<org.envirocar.server.rest.StatisticProto.Statistic.Builder> 
           getStatsBuilderList() {
        return getStatsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.envirocar.server.rest.StatisticProto.Statistic, org.envirocar.server.rest.StatisticProto.Statistic.Builder, org.envirocar.server.rest.StatisticProto.StatisticOrBuilder> 
          getStatsFieldBuilder() {
        if (statsBuilder_ == null) {
          statsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.envirocar.server.rest.StatisticProto.Statistic, org.envirocar.server.rest.StatisticProto.Statistic.Builder, org.envirocar.server.rest.StatisticProto.StatisticOrBuilder>(
                  stats_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          stats_ = null;
        }
        return statsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Statistics)
    }

    // @@protoc_insertion_point(class_scope:Statistics)
    private static final org.envirocar.server.rest.StatisticProto.Statistics DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.envirocar.server.rest.StatisticProto.Statistics();
    }

    public static org.envirocar.server.rest.StatisticProto.Statistics getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Statistics>
        PARSER = new com.google.protobuf.AbstractParser<Statistics>() {
      @java.lang.Override
      public Statistics parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Statistics(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Statistics> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Statistics> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.envirocar.server.rest.StatisticProto.Statistics getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Statistic_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Statistic_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Statistics_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Statistics_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tapp.proto\"h\n\tStatistic\022\013\n\003max\030\001 \002(\001\022\013\n" +
      "\003avg\030\002 \002(\001\022\013\n\003min\030\003 \002(\001\022\023\n\013measurement\030\004" +
      " \002(\003\022\016\n\006tracks\030\005 \002(\003\022\017\n\007sensors\030\006 \002(\003\"\'\n" +
      "\nStatistics\022\031\n\005stats\030\001 \003(\0132\n.StatisticB+" +
      "\n\031org.envirocar.server.restB\016StatisticPr" +
      "oto"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Statistic_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Statistic_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Statistic_descriptor,
        new java.lang.String[] { "Max", "Avg", "Min", "Measurement", "Tracks", "Sensors", });
    internal_static_Statistics_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Statistics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Statistics_descriptor,
        new java.lang.String[] { "Stats", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
